service: nodesimplenote-api
runtime: nodejs16
env: standard
env_variables:
  DBHOST: "34.67.143.103"
  DBNAME: "nodesimplenote"
  DBUSER: "nodeuser"
  DBPASSWORD: "RotiKeju98*"
  DBENGINE: "postgresql"
  APPLICATION_NAME : "node-simple-note-api"
  APPLICATION_TITLE : "Node Simple Note API"
  APPLICATION_PORT : "8080"
  PROJECT : "huda-playground"

